---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.seafile default variables [[[
# =====================================



seafile__deploy_state: "present"


# Packages and installation [[[
# -----------------------------

# .. envvar:: apache__base_packages [[[
#
# List of base packages to install.
seafile__base_packages:
  - 
  - lua-zlib
  - seafile-modules # for ldap auth
#  - lua-event # for use_libevent = true
                                                                   # ]]]
                                                                   # ]]]
# Application user, group, directories [[[
# ----------------------------------------

# .. envvar:: seafile_system_name [[[
#
# Base name for seafile instance
seafile_system_name: 'seafile'

                                                                   # ]]]
# .. envvar:: seafile_user [[[
#
# Name of the system user account for seafile.
seafile_user: '{{ seafile_system_name }}'

                                                                   # ]]]
# .. envvar:: seafile_group [[[
#
# Name of the system group account for seafile.
seafile_group: '{{ seafile_system_name }}'

                                                                   # ]]]
# .. envvar:: seafile_home [[[
#
# Home directory of seafile.
seafile_home: '{{ (ansible_local.root.app
                    if (ansible_local|d() and ansible_local.root|d() and
                        ansible_local.root.app|d())
                    else "/var/local") + "/" + seafile_user }}'

                                                                   # ]]]
seafile__database: 'mysql'

                                                                   # ]]]
# Basic configuration [[[
# -----------------------

# .. envvar:: seafile_version [[[
#
# seafile git version to install.
seafile_version: '6.1.2'

                                                                   # ]]]
# .. envvar:: seafile_source_url [[[
#
# tar.gz source url.
seafile_source_url: 'https://download.seadrive.org/seafile-server_{{ seafile_version }}_x86-64.tar.gz'

                                                                   # ]]]
# .. envvar:: seafile_domain [[[
#
# What domain will be configured for seafile.
seafile_domain: [ 'seafile.{{ ansible_domain }}' ]

                                                                   # ]]]
                                                                   # ]]]
# Database and network [[[
# ------------------------

# .. envvar:: seafile_database_server [[[
#
# FQDN of the MariaDB database host. It will be configured by
# the debops.mariadb_role.
seafile_database_server: '{{ ansible_local.mariadb.server
                              if (ansible_local|d() and ansible_local.mariadb|d() and
                                  ansible_local.mariadb.server|d())
                              else "" }}'

                                                                   # ]]]
# .. envvar:: seafile_database_user [[[
#
# MariaDB database user to use for seafile.
seafile_database_user: '{{ seafile_system_name }}'

                                                                   # ]]]
# .. envvar:: seafile_database_name [[[
#
# Name of the MariaDB database to use for seafile.
seafile_database_name: '{{ seafile_system_name }}'

                                                                   # ]]]
# .. envvar:: seafile_database_password [[[
#
# MariaDB database password for the seafile database user.
seafile_database_password: "{{ lookup('password', secret + '/mariadb/'
                                + (ansible_local.mariadb.delegate_to + '/'
                                   if ansible_local|d() and ansible_local.mariadb|d() and ansible_local.mariadb.delegate_to|d()
                                   else '')
                                + (ansible_local.mariadb.port + '/'
                                   if ansible_local|d() and ansible_local.mariadb|d() and ansible_local.mariadb.port|d()
                                   else '')
                                + '/credentials/' + seafile_database_user + '/password length=48') }}"
                                                                   # ]]]
                                                                   # ]]]

# .. envvar:: seafile__nginx__dependent_servers [[[
#
# Server configuration for the debops.nginx_ Ansible role.
seafile__nginx__dependent_servers:
  - by_role: 'debops.seafile'
    enabled: True
    favicon: False
    name: '{{ seafile_domain }}'
    type: 'proxy'
    proxy_pass: 'http://127.0.0.1:{{ seafile_port }}'
                                                                   # ]]]
                                                                   # ]]]

