---


git_ip:    "{{ (((hostvars['git']   |default({}))['ansible_default_ipv4'])|default({}))['address']|default() }}"

pki_realms:
  - name: 'git.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'cpad.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'calendar.{{ ansible_domain }}'
    acme_default_subdomains: []
  - name: 'account.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []


nginx__servers:
  - enable: True
    name: [ 'git.{{ ansible_domain }}' ]
    acme: True
    type: 'proxy'
    proxy_pass: 'https://git.o-g.at/'
  - enable: True
    name: [ 'calendar.{{ ansible_domain }}' ]
    acme: True
    type: 'proxy'
    proxy_pass: 'https://calendar.o-g.at/'
