---



git_ip:    "{{ (((hostvars['git']   |default({}))['ansible_default_ipv4'])|default({}))['address']|default() }}"


roundcube__default_host: 'tls://mail.{{ ansible_domain }}'
roundcube__smtp_server: 'tls://mail.{{ ansible_domain }}'
roundcube__smtp_port: '587'
roundcube__smtp_user: '%u'
roundcube__smtp_pass: '%p'
roundcube__plugins:
  - 'managesieve'

roundcube__host_local_config_map:
  'managesieve_host': 'tls://mail.{{ ansible_domain }}'
  'mail_domain': '{{ ansible_domain }}'

pki_realms:
  - name: 'git.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'cpad.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'calendar.{{ ansible_domain }}'
    acme_default_subdomains: []
  - name: 'account.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'seafile.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'roundcube.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: '{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: [ 'www' ]


nginx__servers:
  - enable: True
    name: [ '{{ ansible_domain }}', 'www.{{ ansible_domain }}' ]
    acme: True
    #compatible with old system
    location:
      '/': |

      '/pad/': |
        rewrite ^/pad/(.*)$ https://epad.milliways.info/$1 last;
  - enable: True
    name: [ 'git.{{ ansible_domain }}' ]
    acme: True
    type: 'proxy'
    proxy_pass: 'https://git.{{ ansible_domain }}/'
  - enable: True
    name: [ 'calendar.{{ ansible_domain }}' ]
    acme: True
    type: 'proxy'
    proxy_pass: 'https://calendar.{{ ansible_domain }}/'
  - enable: True
    name: [ 'seafile.{{ ansible_domain }}' ]
    acme: True
    location: 
      '/': |
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port  443;
        proxy_pass https://seafile.milliways.info/;
        client_max_body_size 0;
