---



git_ip:    "{{ (((hostvars['git']   |default({}))['ansible_default_ipv4'])|default({}))['address']|default() }}"

pki_realms:
  - name: 'git.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'cpad.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'calendar.{{ ansible_domain }}'
    acme_default_subdomains: []
  - name: 'account.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []
  - name: 'seafile.{{ ansible_domain }}'
    acme: True
    acme_default_subdomains: []


nginx__servers:
  - enable: True
    name: [ 'git.{{ ansible_domain }}' ]
    acme: True
    type: 'proxy'
    proxy_pass: 'https://git.{{ ansible_domain }}/'
  - enable: True
    name: [ 'calendar.{{ ansible_domain }}' ]
    acme: True
    type: 'proxy'
    proxy_pass: 'https://calendar.{{ ansible_domain }}/'
    deny_hidden: false
  - enable: True
    name: [ 'seafile.{{ ansible_domain }}' ]
    acme: True
    location: 
      '/': |
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port  443;
        proxy_pass https://seafile.milliways.info/;
        client_max_body_size 0;
