---

php__sury: True
php__packages: [ 'geoip' ]

cloudadmin_user: 'www-cloudadmin'

cloudldapadmin_dir: '/srv/www/sites/cloudldapadmin'

pki_group_realms:
  - name: 'www.milliways.info'

php__pools:
- name: '{{ cloudadmin_user }}'
  owner: '{{ cloudadmin_user }}'
  home: '/home/{{ cloudadmin_user }}'


# List of nginx upstream definitions
nginx_upstreams: [ '{{ nginx_upstream_php }}' ]

nginx_servers: [ '{{ nginx_servers_cloudldapadmin }}' ]

nginx_servers_cloudldapadmin:
  enable: True
  # Default domain on which this DokuWiki instance will be accessible
  name: [ 'cloudldapadmin.www.milliways.info' ]
  pki_realm: 'www.milliways.info'
  # List of domains which will redirect HTTP requests to main domain
  redirect_from: [ ]
  # User and group which manage this DokuWiki instance (compatible with
  # debops.gitusers role configuration)
  owner: '{{ cloudadmin_user }}'
  group: '{{ cloudadmin_user }}'

  type: 'php'
  php_upstream: 'php_{{ cloudadmin_user }}'
  root: '{{ cloudldapadmin_dir }}/web'

  # List of index files to look for by default
  index: 'index.html index.htm index.php app.php'
  # Definitions of location { } blocks in text block format; there's also
  # 'location_list' with more strict key-value format available)
  location:
    '/': |
      try_files $uri $uri/ @cloudldapadmin;

    '@cloudldapadmin': |
      rewrite ^/(.*)  /app.php  last;


# Upstream for default php5-fpm configuration
nginx_upstream_php:
  enabled: True
  name: 'php_{{ cloudadmin_user }}'
  type: 'php5'
  php5: '{{ cloudadmin_user }}'
#  php_ping_name: 'php-fpm_ping'

php__host_packages: [ 'intl', 'xml', 'zip', 'ldap', 'mysql', 'mbstring' ]

mariadb__client: 'cloudadmin.local'
mariadb__dependent_users:
  - user: cloudadmin
    name: cloudadmin
    state: present

mariadb__dependent_databases:
  - name: 'cloudadmin'

apt_install__packages:
  - 'yui-compressor'

