---


- name: cloudadmin.cloud
  hosts: [ 'debops_cloudldapadmin' ]
  roles:
  - role: debops.ferm
    tags: [ 'role::ferm' ]
    ferm__dependent_rules:
    - type: 'accept'
      weight: '50'
      role: 'cloudadmin'
      protocol: [ 'tcp' ]
      dport: '443'

  - role: debops.nginx
    tags: [ 'role::nginx' ]

  - role: debops.php/env
    tags: [ 'role::php', 'role::apt_preferences', 'role::logrotate' ]

  - role: debops.apt_preferences
    apt_preferences__dependent_list:
    - '{{ php__apt_preferences__dependent_list }}'

  - role: debops.logrotate
    tags: [ 'role::logrotate' ]
    logrotate__dependent_config:
    - '{{ php__logrotate__dependent_config }}'

  - role: debops.mariadb
    tags: [ 'role::mariadb' ]

  - role: debops.php
    tags: [ 'role::php' ]

  tasks:
  - name: install composer
    get_url: url=https://getcomposer.org/composer.phar remote_src=true
      dest=/usr/local/bin/composer
      mode=755
    tags: [ 'task::cloudadmin' ]
  - name: mkdir
    file:
      path: '{{ item }}'
      state: directory
      mode: 0755
      owner: '{{ cloudadmin_user }}'
      group: '{{ cloudadmin_user }}'
      recurse: no
    with_items:
      - /srv/www/sites/cloudldapadmin/
      - /var/www
    tags: [ 'task::cloudadmin' ]
  - name: setup cloudadmin
    include: setup.yml
    #become: true
    #become_user: '{{ cloudadmin_user }}'
    tags: [ 'task::cloudadmin' ]
