---


- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ radicale__base_packages }}'

#- name: copy config
# template:
#   src: 'etc/radicale/radicale.cfg.lua.j2'
#   dest: '/etc/radicale/radicale.cfg.lua'
# notify: [ 'Restart radicale' ]

- lineinfile:
    path: '/etc/default/radicale'
    regexp: '^#?ENABLE_RADICALE='
    line: 'ENABLE_RADICALE=yes'

- name: copy config files
  template:
    src:  'etc/radicale/{{ item }}.j2'
    dest: '/etc/radicale/{{ item }}'
  with_items:
    - 'config'
    - 'rights'

- name: Make sure we have an machine user
  delegate_to: 'ldap.{{ ansible_domain }}'
  ldap_entry:
    dn: '{{ radicale_ldap.dn }}'
    objectClass:
      - simpleSecurityObject
      - organizationalRole
    attributes:
      description: An LDAP machine account
      userPassword: '{{ radicale_ldap.password_hash }}'


- name: Enable Services
  service:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'started'
  with_items:
    - radicale

