---
- name: install composer
  get_url: url=https://getcomposer.org/composer.phar remote_src=true
    dest=/usr/local/bin/composer
    mode=755
  tags: [ 'task::cloudadmin' ]
- name: mkdir
  file:
    path: '{{ lenticular_admin__dir }}'
    state: directory
    mode: 0750
    owner: '{{ lenticular_admin__user }}'
    group: '{{ lenticular_admin__user }}'
    recurse: no
  tags: [ 'task::cloudadmin' ]
- name: setup cloudadmin
  include: setup.yml
#  become: true
#  become_user: '{{ lenticular_admin__user }}'
  tags: [ 'task::cloudadmin' ]
