---

- name: Manage Prosody
  hosts: [ 'debops_service_radicale' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:
    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx__dependent_servers:
        - '{{ radicale__nginx__dependent_servers }}'

    - role: debops.radicale
      tags: [ 'role::radicale' ]

