---



- name: Manage Lenticular Admin
  hosts: [ 'debops_service_lenticular_admin' ]
  roles:
  - role: debops.apt_preferences
    apt_preferences__dependent_list:
    - '{{ php__apt_preferences__dependent_list }}'
  - role: debops.php/env
    tags: [ 'role::php', 'role::apt_preferences', 'role::logrotate' ]
  - role: debops.php
    tags: [ 'role::php' ]
    php__dependent_packages: '{{ lenticular_admin__php_host_packages }}'
    php__dependent_pools: '{{ lenticular_admin__php__pools }}'
  - role: debops.nginx
    tags: [ 'role::nginx' ]
    nginx__dependent_servers:
        - '{{ lenticular_admin__nginx__dependent_servers }}'
    nginx__dependent_upstreams:
        - '{{ lenticular_admin__nginx_upstream_php }}'
  - role: debops.logrotate
    tags: [ 'role::logrotate' ]
    logrotate__dependent_config:
    - '{{ php__logrotate__dependent_config }}'
  - role: debops.mariadb
    tags: [ 'role::mariadb' ]
    mariadb__dependent_users: '{{ lenticular_admin__mariadb__dependent_users }}'
    mariadb__dependent_databases: '{{ lenticular_admin__mariadb__dependent_databases }}'
  - role: debops.lenticular_admin
    tags: [ 'role::lenticular_admin' ]



